dist: bionic
language: go
go:
- 1.13.x
env:
  - GO111MODULE=on CGO_ENABLED=0

sudo: required

services:
  - docker

install:
  - go mod tidy

# Don't email me the results of the test runs.
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ec30ac1bb280c976f8be
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# Anything in before_script that returns a nonzero exit code will
# flunk the build and immediately stop. It's sorta like having
# set -e enabled in bash.
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2
  - go get github.com/mattn/goveralls

# script always run to completion (set +e). All of these code checks are must haves
# in a modern Go project.
script:
  - make lint
  - make test

# If the build succeeds, send coverage to coveralls
# goreleaser will run if the latest version tag matches the current commit
after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  - if [[ "$TRAVIS_SECURE_ENV_VARS" == true && "$TRAVIS_GO_VERSION" == 1.13* ]]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; curl -sL https://git.io/goreleaser | bash; fi
