dist: bionic
language: go
go:
- 1.13.x

services:
- docker

before_script:
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1

script:
- make lint
- make test
