name: CI

on: push

jobs:
  test:
    name: Go ${{ matrix.go-version }} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    # See https://github.com/actions/setup-go/issues/14
    - name: Setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    - name: Install dependencies
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2

    - name: Run test suite
      run: make test

    - name: Run linter
      run: make lint
