name: CI

on: push

jobs:
  test:
    name: Go ${{ matrix.go-version }} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run test suite
      run: make test

    - name: Run linter
      run:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2
      - make lint
